changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: breaking changes
      labels:
        - breaking
    - title: features
      labels:
        - enhancement
    - title: fixes
      labels:
        - bug
    - title: maintenance
      labels:
        - "*"
